# Generated by Django 2.0.5 on 2018-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('device_type', models.CharField(choices=[('1', 'sensor'), ('2', 'gateway')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'online'), ('2', 'offline')], max_length=1)),
            ],
        ),
    ]
